### ISSUE TITLE
Post Github Release with github action

### ISSUE THREAD

**Issue by liangyuanpeng** [etcd-io/jetcd#1242]
Now, github release of Jetcd staying at `jetcd-0.6.1` , Let us try to restore jetcd's github release. In order to reduce maintenance pressure, use github action to automate the release process. 

let me work for it if possible.

Any thought?  @lburgazzoli

**Comment by liangyuanpeng** [comment]
Some Note that i just talking about github release and not release java jar.

**Comment by lburgazzoli** [comment]
Yes but since the release is a manual process, then the github release can ideally be done by the gradle build script.
Not sure how that could be done by a GitHub action, mind explaining what you have in mind ?

**Comment by liangyuanpeng** [comment]
Create a new github release with github action when a new tag of `jetcd-*` is pushed.

```yaml
on:
  push:
    tags:
      - "jetcd-*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
...
```

Does it make sense?
